apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: cithit/taylorw8:latest
        ports:
        - containerPort: 7000
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: default
spec:
  selector:
    app: backstage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7000
---
# Include other resources like ConfigMaps, Secrets, or Ingress as needed.
