version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: backstage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backstage:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backstage
    ports:
      - "7000:7000"

volumes:
  postgres_data:
